package mcptools

// --- MCP Tool Types for the decompose server mode (--serve-mcp) ---
// These tools are exposed when the binary runs as an MCP server for Claude Code.
// They allow the /decompose skill to call structured tools instead of shelling out.

// RunStageInput is the input for the run_stage MCP tool.
type RunStageInput struct {
	Name        string `json:"name" jsonschema:"decomposition name (kebab-case)"`
	Stage       int    `json:"stage" jsonschema:"pipeline stage to run (0-4)"`
	ProjectRoot string `json:"projectRoot,omitempty" jsonschema:"path to the target project (default: cwd)"`
}

// RunStageOutput is the result of the run_stage MCP tool.
type RunStageOutput struct {
	FilesWritten []string `json:"filesWritten"`
	Stage        int      `json:"stage"`
	Status       string   `json:"status"` // "completed" or "failed"
	Message      string   `json:"message,omitempty"`
}

// GetStatusInput is the input for the get_status MCP tool.
type GetStatusInput struct {
	Name string `json:"name" jsonschema:"decomposition name"`
}

// GetStatusOutput is the result of the get_status MCP tool.
type GetStatusOutput struct {
	Name            string `json:"name"`
	CompletedStages []int  `json:"completedStages"`
	NextStage       int    `json:"nextStage"`
	CapabilityLevel string `json:"capabilityLevel"`
}

// ListDecompositionsInput is the input for the list_decompositions MCP tool.
type ListDecompositionsInput struct {
	ProjectRoot string `json:"projectRoot,omitempty" jsonschema:"path to the project (default: cwd)"`
}

// ListDecompositionsOutput is the result of the list_decompositions MCP tool.
type ListDecompositionsOutput struct {
	Decompositions []DecompositionSummary `json:"decompositions"`
	HasStage0      bool                   `json:"hasStage0"`
}

// DecompositionSummary is a brief overview of one decomposition.
type DecompositionSummary struct {
	Name            string `json:"name"`
	CompletedStages []int  `json:"completedStages"`
	NextStage       int    `json:"nextStage"`
}

// --- Hybrid tool types (Claude generates content, binary validates + writes) ---

// SectionInput is a named section of content generated by Claude.
type SectionInput struct {
	Name    string `json:"name" jsonschema:"section name matching the template section order (e.g. 'assumptions', 'data-model')"`
	Content string `json:"content" jsonschema:"the markdown content for this section"`
}

// WriteStageInput is the input for the write_stage MCP tool.
type WriteStageInput struct {
	Name     string         `json:"name" jsonschema:"decomposition name (kebab-case)"`
	Stage    int            `json:"stage" jsonschema:"pipeline stage (0-4)"`
	Sections []SectionInput `json:"sections" jsonschema:"ordered list of sections with name and content"`
}

// WriteStageOutput is the result of the write_stage MCP tool.
type WriteStageOutput struct {
	FilesWritten    []string `json:"filesWritten"`
	CoherenceIssues []string `json:"coherenceIssues,omitempty"`
	Status          string   `json:"status"` // "completed" or "failed"
	Message         string   `json:"message,omitempty"`
}

// GetStageContextInput is the input for the get_stage_context MCP tool.
type GetStageContextInput struct {
	Name  string `json:"name" jsonschema:"decomposition name (kebab-case)"`
	Stage int    `json:"stage" jsonschema:"pipeline stage (0-4)"`
}

// GetStageContextOutput is the result of the get_stage_context MCP tool.
type GetStageContextOutput struct {
	StageName      string   `json:"stageName"`
	SectionNames   []string `json:"sectionNames"`
	Prerequisites  string   `json:"prerequisites,omitempty"`
	Template       string   `json:"template"`
	GraphAvailable bool     `json:"graphAvailable"`
	InputContent   string   `json:"inputContent,omitempty"`
}

// SetInputInput is the input for the set_input MCP tool.
type SetInputInput struct {
	Name     string `json:"name" jsonschema:"decomposition name (kebab-case)"`
	FilePath string `json:"filePath,omitempty" jsonschema:"path to a high-level input file (idea, spec, or plan)"`
	Content  string `json:"content,omitempty" jsonschema:"inline content (used if filePath is empty)"`
}

// SetInputOutput is the result of the set_input MCP tool.
type SetInputOutput struct {
	Status       string `json:"status"`
	ContentBytes int    `json:"contentBytes"`
}
